name: Check for New Prog Messages

on:
  schedule:
    - cron: '*/10 * * * *'  # כל 10 דקות
  workflow_dispatch:        # מאפשר גם הפעלה ידנית

permissions:
  contents: write

jobs:
  check-prog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create output directory
        run: mkdir -p out

      - name: Compile Java code
        run: |
          javac -cp "lib/*" -d out ForumNotifier.java

      - name: Run Prog Checker
        run: |
          java -cp "out:lib/*" ForumNotifier

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last.txt
          git diff --cached --quiet || git commit -m "Update last.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
